# Generated by Django 4.0.3 on 2022-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220410_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
